# - name: Installing Nginx
#   hosts: frontend
#   become: yes
#   tasks:
#   - name: install nginx
#     ansible.builtin.package:
#       name: nginx
#       state: present

  
#   - name: start nginx
#     ansible.builtin.service:
#       name: nginx
#       state: started
#       enabled: yes

- name: install nginx
  hosts: frontend
  because: yes
  tasks:
  - name: install
    ansible.builtin.package:
      name: nginx
      state: present

  - name: start nginx
    ansible.builtin.service:
      name: nginx
      start: started
