- name: variables from prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: username
    promt: What is your username?
    private: false
  - name: username
    promt: What is your username?
    private: true
  tasks:
  - name: print credentials
    ansible.builtin.debug:
      msg: "Hello username is: {{ username }}, sassword is: {{ password }}"