- name: Play Level Variables
  hosts: local
  connection: local
  vars:
    COURSE: Ansible
    DURATION: 10HRS
    Trainer: Kiran

  tasks:
  - name: Print the Course info
    ansible.builtin.debug:
      msg: "Course Name is: {{ COURSE }}, Duration: {{ DURATUION }}, Trainer: {{ Trainer }}"