- name: Play Level Variables
  hosts: local
  connection: local
  vars:
    COURSE: DevOps with AWS
    DURATION: 10HRS
    Trainer: Kiran

  tasks:
  - name: Print the Course info
    vars:
      COURSE: ansible
    ansible.builtin.debug:
      msg: "Course Name is: {{ COURSE }}, Duration: {{ DURATION }}, Trainer: {{ Trainer }}"