- name: data types
  hosts: local
  connection: local
  vars:
    Course: "Cloud"
    Duration: 120
    is_live: true

    tools:
    - "linux"
    - "shell"
    - "ansible"

    concepts:
      cloud: aws
      cm: ansible

  tasks:
  - name: print course info
    ansible.builtin.debug:
      msg: "Course name: {{ Course }}, Duration: {{ Duration }}, is it_live?: {{ is_live }}, tools are: {{ tools }} concepts are: {{ concepts }}"