- name: functions
  hosts: local
  connection: local
  vars:
    technologies: DevOps, Linux, Shell Scripting, Ansible
    name: Kirankumar K
    gmail: KOSURIKIRAN@7GMAIL.COM
    ipaddress: 123.2345.23456.234
    # dictionary == map
    tags:
      Application: payment
      Environment: dev
    listTages:
    - key: Application
      value: payment
    - key: Environment
      value: dev
  tasks:
  - name: default variables
    ansible.builtin.debug:
      msg: "Hello, {{ name | default('Kiran') }}"

# String to List

  - name: Convert String to List 
    ansible.builtin.debug:
      msg: "Technologies are: {{ technologies | split(',') }}"

  - name: Converting Mao to List
    ansible.builtin.debug:
      msg: "Tags are: {{ tags | dict2items }} "

  - name: Converting Map to List
    ansible.builtin.debug:
      msg: "Tags Map: {{  listTages | items2dict }}"

  - name:  convert lowercase
    ansible.builtin.debug:
      msg: "{{ name | upper }}"

  - name: convert lower case
    ansible.builtin.debug:
      msg: "{{ gmail | lower }}"

  - name: check IP is valid or not
    ansible.builtin.debug:
    msg: "{{ ipaddress | ansible.utils.ipv4 }}"

  