#Functions in Ansible

- name: Functions
  hosts: local
  connection: local
  vars:
    technologies: DevSecOps, Linux, Shell Scripting, Ansible
    name: Kirankumar k
    names: KIRAN KUMAR KOSURI
    gmail: Kiran@GMAIL.COM
    ipaddress: 192.168.0.1
    tags:
      Application: payment
      Environment: DevOps
    listTags:
    - key: Application
      value: payment
    - key: Environment
      value: dev

  tasks:
  - name: default variables
    ansible.builtin.debug:
      msg: "Hello, {{ name | default('Kiran') }}"

  #String to List
   
  - name: convert string to List
    ansible.builtin.debug:
      msg: "Technolgies are: {{ technologies | split(',') }}"

  - name: convert map to list
    ansible.builtin.debug:
      msg: "Tags are: {{ tags | dict2items }}"

  - name: convert list into map
    ansible.builtin.debug:
      msg: "Tag map: {{ listTags | items2dict }}"

  - name: convert uppercase 
    ansible.builtin.debug:
      msg: "{{ name | upper }}"

  - name: convert lowercase 
    ansible.builtin.debug:
      msg: "{{ names | lower }}"

  - name: convert to lower case
    ansible.builtin.debug:
      msg: "{{ gmail | lower }}"

  - name: check ip is valid or not
    ansible.builtin.debug:
      msg: "{{ ipaddress | ansible.utils.ipv4 }}"

  - name: grep for root
    ansible.builtin.shell: cat /etc/passwd/ | grep root
    register: command_output

  - name: print the command_output
    ansible.builtin.debug:
      msg: "{{ command_output }}"

